- name: Run MLflow Project (no conda)
  run: |
    cd MLProject
    export MLFLOW_TRACKING_URI="file:./mlruns"
    export MLFLOW_EXPERIMENT_NAME="ci_experiment"
    mlflow run . -e main --env-manager local
